import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Globe, Smartphone, QrCode, Music, Users, Play } from 'lucide-react';

export default function HowToPlayPage() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-paper-texture p-4 md:p-8">
      <div className="max-w-4xl mx-auto">
        <button onClick={() => navigate('/')} className="flex items-center gap-2 text-polaroid-light hover:text-polaroid mb-6 transition-colors"><ArrowLeft className="w-5 h-5" />На главную</button>
        <div className="text-center mb-8">
          <div className="text-polaroid-accent text-3xl mb-2 font-title tracking-widest">✦ ✦ ✦</div>
          <h1 className="text-3xl font-serif-old font-bold text-polaroid mb-2">Как играть</h1>
          <p className="text-polaroid-light font-typewriter">Полная инструкция</p>
          <div className="text-polaroid-accent text-3xl mt-2 font-title tracking-widest">✦ ✦ ✦</div>
        </div>
        <div className="space-y-6">
          <div className="polaroid-card"><h2 className="text-polaroid text-xl font-serif-old font-bold mb-4 flex items-center gap-2"><Globe className="w-6 h-6 text-polaroid-accent" />Как открыть сайт</h2><div className="space-y-4 text-polaroid-light font-typewriter"><div><p className="text-polaroid font-semibold mb-2">Вариант 1: Локально</p><div className="bg-polaroid-cream rounded p-4 font-mono text-sm"><p className="text-polaroid-accent"># Скачайте и запустите</p><p className="text-polaroid">git clone https://github.com/HorrorStoryy/music_bingo.git</p><p className="text-polaroid">cd music_bingo && npm install && npm run dev</p><p className="text-polaroid-accent mt-2"># Откройте:</p><p className="text-polaroid">http://localhost:3000</p></div></div><div><p className="text-polaroid font-semibold mb-2">Вариант 2: GitHub Pages</p><p className="text-sm">Сайт доступен по адресу: <code className="text-polaroid-accent">https://HorrorStoryy.github.io/music_bingo/</code></p></div></div></div>
          <div className="polaroid-card"><h2 className="text-polaroid text-xl font-serif-old font-bold mb-4 flex items-center gap-2"><Users className="w-6 h-6 text-polaroid-accent" />Как играть</h2><div className="space-y-3 font-typewriter text-polaroid-light"><div className="flex gap-4"><div className="w-10 h-10 bg-polaroid-accent/20 rounded-xl flex items-center justify-center flex-shrink-0"><span className="text-polaroid-accent font-bold">1</span></div><div><p className="text-polaroid font-semibold">Админ входит</p><p className="text-sm">Логин: <code className="text-polaroid-accent">admin</code> / Пароль: <code className="text-polaroid-accent">admin</code></p></div></div><div className="flex gap-4"><div className="w-10 h-10 bg-polaroid-accent/20 rounded-xl flex items-center justify-center flex-shrink-0"><span className="text-polaroid-accent font-bold">2</span></div><div><p className="text-polaroid font-semibold">Админ создаёт плейлисты</p><p className="text-sm">Добавьте треки через ссылки (Google Drive, YouTube, MP3)</p></div></div><div className="flex gap-4"><div className="w-10 h-10 bg-polaroid-accent/20 rounded-xl flex items-center justify-center flex-shrink-0"><span className="text-polaroid-accent font-bold">3</span></div><div><p className="text-polaroid font-semibold">Хост создаёт игру</p><p className="text-sm">Нажмите "Создать игру" → выберите плейлист → получите код</p></div></div><div className="flex gap-4"><div className="w-10 h-10 bg-polaroid-accent/20 rounded-xl flex items-center justify-center flex-shrink-0"><span className="text-polaroid-accent font-bold">4</span></div><div><p className="text-polaroid font-semibold">Игроки подключаются</p><p className="text-sm"><Smartphone className="w-4 h-4 inline" /> Введите код или отсканируйте <QrCode className="w-4 h-4 inline" /> QR-код</p></div></div><div className="flex gap-4"><div className="w-10 h-10 bg-polaroid-accent/20 rounded-xl flex items-center justify-center flex-shrink-0"><span className="text-polaroid-accent font-bold">5</span></div><div><p className="text-polaroid font-semibold">Игра начинается!</p><p className="text-sm">Хост включает треки. Название НЕ показывается — угадывайте на слух!</p></div></div><div className="flex gap-4"><div className="w-10 h-10 bg-polaroid-accent/30 rounded-xl flex items-center justify-center flex-shrink-0"><span className="text-polaroid-accent font-bold">🏆</span></div><div><p className="text-polaroid font-semibold">Победа!</p><p className="text-sm">Кто первый закроет все 15 ячеек — победил!</p></div></div></div></div>
          <div className="polaroid-card"><h2 className="text-polaroid text-xl font-serif-old font-bold mb-4 flex items-center gap-2"><Play className="w-6 h-6 text-polaroid-accent" />Как добавить клипы</h2><div className="space-y-3 text-polaroid-light font-typewriter text-sm"><p className="text-polaroid font-semibold">Для админа:</p><ol className="space-y-2"><li>1. В панели админа создайте новый плейлист</li><li>2. Добавьте треки (название + исполнитель)</li><li>3. Вставьте ссылку на Google Drive / YouTube / MP3</li><li>4. Сохраните плейлист</li></ol><div className="bg-polaroid-cream rounded p-3 border border-polaroid mt-3"><p className="text-polaroid-accent font-semibold mb-1">💡 Примеры ссылок:</p><ul className="text-xs space-y-1"><li>• Google Drive: <code className="text-polaroid">https://drive.google.com/file/d/FILE_ID/view</code></li><li>• YouTube: <code className="text-polaroid">https://youtube.com/watch?v=VIDEO_ID</code></li><li>• MP3: <code className="text-polaroid">https://example.com/song.mp3</code></li></ul></div></div></div>
        </div>
      </div>
    </div>
  );
}
